### ISSUE TITLE
[doubt] is there any way i can install the version of the rice with the ags bar

### ISSUE THREAD

**Issue by nichroot** [yashlakhtariya/ysl-hyprdots#1]

**Comment by yashlakhtariya** [comment]
Older version v1 contains older syntax for config files so it won't work with newer versions of hyprland

I've added new configuration for ags in upcoming version. Will update as soon as possible after proper testing

**Comment by yashlakhtariya** [comment]
added v4 with ags configurations if you prefer it over waybar

To use ags :
- Uncomment agspanel line in userprefs.conf and comment dunst, waybar exec lines in hyprland.conf
- Copy ags config directory and ags-cache dir as name 'ags' in .cache directory for using same options configured my me

**Comment by nichroot** [comment]
yo can you update the images and add v4 too to the readme?

**Comment by yashlakhtariya** [comment]
It will be too messy for readme, check this ags panel if you want that config, it is included in v4 : 

![Screenshot_20240924_084125](https://github.com/user-attachments/assets/f40a5a54-88ea-4953-acee-7f325a318415)
![Screenshot_20240924_084141](https://github.com/user-attachments/assets/ecac0917-df75-497d-a4c2-da4f22545bf2)

The dock you can use any configuration, check userprefs.conf and dock variables, there are light, dark, different corners, left, bottom configs there

Also you can use different color combinations for light, dark Material You like colors for ags panel, it is based on 

> https://github.com/Jas-SinghFSU/HyprPanel

Happy ricing!!!
