### ISSUE TITLE
How to get that dock

### ISSUE THREAD

**Issue by pranshunotpriyanshu** [yashlakhtariya/ysl-hyprdots#2]
How do you actually get that beautiful dock on your setup, what app to install, I don't see any theme for nwg-dock too, so how to get it, btw, it's verryyyyy beautiful.

**Comment by yashlakhtariya** [comment]
@IUseArchBTW-monooo Glad you liked the dock themes!!! 

To use it you must install **nwg-dock-hyprland** and use my configs. In **userprefs.conf** I have set dock configs in **$dock** variable, in my repo's config dir, you will get nwg-dock and nwg-drawer folders, copy them in your .config and use your preferred dock theme in userprefs.conf

**Comment by pranshunotpriyanshu** [comment]
Thanks
